### ISSUE TITLE
Include subdivision terminology

### ISSUE THREAD

**Issue by backus** [countries/countries#171]
I would like to add first-level subdivision terminology to the country data.  In other words, given a country we know which of the following terms it uses:
- State
- Region
- Territory
- Province
- Prefecture
- Governorate
- Department
- County
- Canton
- Parish
- District
- Municipality

I would base this information off of Wikipedia's [Matrix of Country Subdivisions](https://en.wikipedia.org/wiki/Matrix_of_country_subdivisions) and the [ISO 3166-2 primary codes](https://en.wikipedia.org/wiki/ISO_3166-2#Current_codes) which I could probably pull from [oodavid's iso_3166_2.js](https://github.com/oodavid/iso-3166-2/blob/master/iso_3166_2.js).  Would a pull request be welcome?

**Comment by rposborne** [comment]
I think this and #186 need to be thought about together.

**Comment by aviemet** [comment]
Wondering if this was ever implemented?

I'm not sure how to use this gem to build an international address input form without that information.

**Comment by aviemet** [comment]
#649 I created a pull request with what I thought could be an implementation of this feature. I drew the information from the Wikipedia article mentioned in @backus comment. 

My intention was to add information to the country object which could be used as a label for address inputs. I settled on `subdivision_name`, and for some of the countries I ended up using a '/' if they used more than 1 name. For instance, in Canada the subdivision_name is 'Territory/Province'. Not sure if this is in line with the issue in #186 , but I believe it's a better solution than an array for the case of labeling inputs.

**Comment by pmor** [comment]
#758 has added the ISO subdivision types
