### ISSUE TITLE
Simplified and Traditional Chinese

### ISSUE THREAD

**Issue by jash** [countries/countries#280]
I notice that there is only one "Chinese" translation available for countries.  However, there are two primary Chinese character sets that are in use: Simplified Chinese and Traditional Chinese characters.

Various projects will use zh-CN or zh-Hans to contain Simplified Chinese and zh-TW or zh-Hant to contain Traditional Chinese translations.

Right now this project only has "zh" which seems to contain Simplified Chinese characters.  Would it be possible to add Traditional Chinese characters as well?  What language code should be used?

**Comment by rposborne** [comment]
Yes we should be able to add an entire locale via the translation_override.yaml, As for which key, I am by far an expert in the matter, matching standards is most likely best, so I am leaning towards zh-TW,

**Comment by pmor** [comment]
We've had `zh_CN` , `zh_HK` and `zh_TW` translations for a while. Closing.
