### ISSUE TITLE
Organization Rehaul

### ISSUE THREAD

**Issue by rposborne** [countries/countries#338]
- [ ] Transfer repo to countries repo to countries org
- [ ] Land on common specification for organizing data that allows selective importing (i.e; only alpha2 codes, or alpha2 and translations, or only mailing addresses.)
- [ ] Move i18n_data to CLDR, country translations, 
- [ ] Split Gem into countries-data and countries-rb (we will retain the original gem name)
- [ ] Open countries org up to other language implementations.

@hexorx, this is my current plan to let countries continue to grow / become easier to maintain

This is also a call to arms for others looking to help out in open source. @kwals

**Comment by kwals** [comment]
@rposborne I'm willing to help with moving the data. Do we have the org setup?

**Comment by rposborne** [comment]
@hexorx Can I get a higher permission level on the countries org than just member?  Expect to have some time soon and would like to roll on this. 

@kwals We do, but currently empty.  If you can starting determining the feasibility of getting a good data set out of the [CLDR](http://cldr.unicode.org/)

**Comment by hexorx** [comment]
Done.

On Wed, May 18, 2016 at 8:37 AM, rocketosborne <notifications@github.com>
wrote:

> @hexorx <https://github.com/hexorx> Can I get a higher permission level
> on the countries org than just member? Expect to have some time soon and
> would like to roll on this.
>
> @kwals <https://github.com/kwals> We do, but currently empty. If you can
> starting determining the feasibility of getting a good data set out of the
> CLDR <http://cldr.unicode.org/>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/hexorx/countries/issues/338#issuecomment-220046428>
>



-- 
@JoshRobinson

**Comment by pmor** [comment]
Cleaning up old issues. Some of this has already been worked on, or looked into, while the rest is no longer relevant
