### ISSUE TITLE
Add official name attribute

### ISSUE THREAD

**Issue by dankimio** [countries/countries#453]
The [ISO standard](https://www.iso.org/obp/ui/#iso:code:3166:CZ) and the [package](https://anonscm.debian.org/cgit/pkg-isocodes/iso-codes.git/tree/data/iso_3166-1.json) contain official (full) names of the countries.

Currently, there's no way of getting the official name of the country unless it is the same as the short one. For example, the official name of Czechia is Czech Republic, which is listed in `unofficial names`.

The `official_name` (or `full_name`) attribute should solve the problem.

**Comment by pmor** [comment]
#717 has been merged and released
