### ISSUE TITLE
Add country_code to HM, PN and UM

### ISSUE THREAD

**Issue by TarasBardiuk** [countries/countries#477]
Heard Island and McDonald Islands: 0
Pitcairn: 64
United States Minor Outlying Islands: 1

**Comment by TarasBardiuk** [comment]
@hexorx, help, please

**Comment by rposborne** [comment]
@TarasBardiuk We are always looking for additions, but this project, as are most on GitHub are managed out of love, please don't demand someone's attention. 

Please submit a pull-request for the changes that you would like to have made.

**Comment by rposborne** [comment]
Also please provide references to these changes. I am able to track down Pitcairn, but I cannot find Heard Island.

**Comment by pmor** [comment]
Looks like this was fixed at some point
