### ISSUE TITLE
Subdivision code always nil

### ISSUE THREAD

**Issue by algodave** [countries/countries#484]
I would expect the `code` attribute in `::Subdivision` to have the same value as the key in its country's `states` Hash.
 
```ruby
usa = ISO3166::Country.find_country_by_alpha2('US')
# => #<ISO3166::Country:0x00007f9b14beb548 ... >
usa.states['AL'].code.eql?('AL')
# => false
usa.states['AL']
# => #<struct ISO3166::Subdivision name="Alabama", code=nil, unofficial_names="Alabama", ... >
```

Or maybe I'm wrong? Is the `code` attribute meant to be used for something else?

**Comment by JalisoCSP** [comment]
Code in subdivision seems to be unused, but according to the CHANGELOG was added in 2.1.1 by @kasparsj

The PR comment says "it can be handy when using custom data or ISO3166::Data.register"

Change -> https://github.com/hexorx/countries/blob/master/CHANGELOG.md#211
Commit -> https://github.com/hexorx/countries/commit/85017d932f4bbfb93f1917c354666d343ad0abc7
PR -> https://github.com/hexorx/countries/pull/461
