### ISSUE TITLE
Jersey uses GBP instead of JEP currency

### ISSUE THREAD

**Issue by dsbonev** [countries/countries#492]
Here is the official data https://www.currency-iso.org/dam/downloads/lists/list_one.xml
JEP is not part of the standard, i.e. it is [unofficial with limited usage](https://en.wikipedia.org/wiki/ISO_4217#Unofficial_currency_codes). 
Let's remove JEP and use GBP in its place.

**Comment by timkrins** [comment]
Is there a particular reason to remove it?

I happen to live in Jersey, and yes, we do use GBP, but unless there is a specific reason to remove JEP, I don't see why keeping it would be a negative.

Most banknotes you will find here are JEP, and cannot be used as legal tender in the UK.

Other libraries, such as ruby/money, also have JEP, and most software developers dealing with Jersey would be aware of when they want to use either GBP or JEP.

**Comment by dsbonev** [comment]
The particular reason is that the software that our team develops is sold worldwide and we accept certain currencies based on the user's country, e.g. GBP for UK clients, AUD for Australian clients, etc. and USD is the default for the rest of the world. Apparently Jersey clients would like to pay in GBP instead of in USD, we do not accept payments in JEP. Then I checked the standard and according to it the GBP is the official currency in Jersey instead of JEP.

**Comment by timkrins** [comment]
Okay. There are a few edge cases you should be aware of then -

Jersey, Guernsey, and Gibraltar all use GBP, all pegged 1:1 to the local currency.

If people are using this as a source of truth about a countries accepted currency then I can understand that changing it would be useful.

**Comment by dsbonev** [comment]
Thanks, what you described is pretty close to how we handled the issue in our product. 

To add to this issue request, let's change Isle of Man's currency to GBP as well, so that it would follow the standard. Presently, we have one country that follows the standard and two which do not, this is inconsistent and one cannot rely on fully standard currencies or fully non-standard ones returned by the gem:

Country | ISO | Unofficial | gem 
----------|---------------|----------------------|-----------------
Guernsey | GBP | GGP | GBP (ISO)
Isle of Man | GBP | IMP | IMP (Unofficial)
Jersey | GBP | JEP | JEP (Unofficial)

I haven't included Gibraltar as it does not use GBP per the ISO and the gem matches the standard.
