### ISSUE TITLE
Double translation for Slovakia?

### ISSUE THREAD

**Issue by wvengen** [countries/countries#517]
When requesting the Dutch translation for Slovakia (SK), I find _"Slowakije, Slovakije"_ (countries 2.0.8). It looks like the translation has two variations in a single string, shouldn't it be better to pick one ([_Slowakije_](https://nl.wikipedia.org/wiki/Slowakije)) and put the other in `unofficial_names`?

**Comment by pmor** [comment]
This appears to have been fixed.
