### ISSUE TITLE
Fails to get Ukraine country code (+38)

### ISSUE THREAD

**Issue by Hamsy99tests** [countries/countries#522]
Fails to get the Ukraine country (+38) from ISO3166. Please add asap.

**Comment by rposborne** [comment]
@Hamsy99tests would you mind submitting a PR to add this content?

**Comment by sam-kim** [comment]
Isn't Ukraine's country code +380?

```ruby
[11] pry(main)> ISO3166::Country.new('UA').data["name"]
=> "Ukraine"
[12] pry(main)> ISO3166::Country.new('UA').data["country_code"]
=> "380"
```

```Due to the last digit of the country code (+380) being identical to the trunk prefix (0), international format numbers are often presented as +38 0..., e.g. the (fictional) Kiev number +38 044 555 1234. +38 belonged to Yugoslavia before its disintegration in the early 1990s, and the +38 code was broken up and distributed amongst the former republics. +380 went to Ukraine, which previously used the +7 code.```
[source](https://en.wikipedia.org/wiki/Telephone_numbers_in_Ukraine)
