### ISSUE TITLE
Countries added with Data.register not in Country.all_translated

### ISSUE THREAD

**Issue by wmnnd** [countries/countries#550]
Since `ISO3166::Country.all_translated` seems to use data from `i18n_data` instead of the data managed by this gem, countries added with `ISO3166::Data.register` or to the YAML definitions of `countries` don’t show up there:

```ruby
ISO3166::Data.register(
    alpha2: 'LOL',
    name: 'Happy Country',
    translations: {
    'en' => 'Happy Country'
    }
)
puts ISO3166::Country.all_translated('de').find { |i| i.include? "Happy"} # => nil
puts ISO3166::Country['lol'].name #> 'Happy Country'
```

Would you accept a PR that modifies the `all_translated` to do the following?
```ruby
def translations(locale = 'en')
  i18n_data_countries = I18nData.countries(locale.upcase)
  custom_countries = (ISO3166::Data.codes - i18n_data_countries.keys).map do |code|
    country = ISO3166::Country[code]
    translation = country.translations[locale] || country.name
    [code, translation]
  end.to_h
  i18n_data_countries.merge(custom_countries)
end
```

**Comment by cameronbourgeois** [comment]
I have run into this issue today @wmnnd and agree that the above proposed solution makes sense.

**Comment by ImBobby** [comment]
I have similar issue. I register new country but does not show up on `ISO3166::Country.all`.

**Comment by pmor** [comment]
This has been fixed.
