### ISSUE TITLE
2.2.0 - breaking change for users of the currencies extension

### ISSUE THREAD

**Issue by lukaVarga** [countries/countries#556]
Hi,

First off, thanks for this gem :) It's awesome to be able to use it.

After the recent 2.2.0 release, I've noticed some issues with uninitialized constants whenever trying to do something with the `Money` class. Eg. `ActionView::Template::Error (uninitialized constant ActionView::CompiledTemplates::Money)`

I tracked this down and it looks like [this commit](https://github.com/hexorx/countries/commit/0bbbe08a490db4a9e702d43f0892dbe81d6acada) actually introduced a breaking change as the currency extension is now turned off by default, whereas it was working by default in 2.1.x

So, to fix it, one has to add `ISO3166.configuration.enable_currency_extension!` into the countries initializer.

I suggest, considering the version change was minor, a patch version is released that would turn on the currency extension by default and then maybe consider turning it off by default when a major version is released.

**Comment by rposborne** [comment]
@lukaVarga I agree I didn't realize it was off be default i'll get a patch out asap.

**Comment by rposborne** [comment]
@lukaVarga I think it may be much simpler to yank 2.2.0 and re release it as 3.0.  As we dropped having money as a dependency. I had flagged it as a breaking change when it was merged but it has slipped my mind when I was releasing the other day.

**Comment by lukaVarga** [comment]
@rposborne thanks for the quick reply :)
If you drop 2.2 and re-release it as 3.0, the builds (eg. on heroku) will probably start failing for those who've already upgraded to 2.2 as the bundler won't be able to resolve the 2.2 version. 
I think the most proper way would be to re-release 2.2 without merging in the commit that was a breaking change so the 2.2 version doesn't suddenly vanish, and then merge in that commit and release the 3.0 - if that's possible within the gem ecosystem. If not, I would say a patch version that reverts that merge + 3.0 release are the safest bets to ensure nothing else breaks.

**Comment by rposborne** [comment]
you are absolutely correct,  but it would still be broken for those who upgraded to 2.2 for this feature.   I don't think there is a perfect solution here, unless I add some type of method shim that re implements the configuration call for the currency code, which I simply do not have time to do.

I assume there is a long tail for those who upgrade.  We still have very low download counts for 2.2, so I assumed that measured amount of risk.

**Comment by pmor** [comment]
Closing, as we're now at version 4.1 and this should no longer be relevant
