### ISSUE TITLE
Should the first unofficial name for `KP` be "North Korea" instead of "Korea (North)"?

### ISSUE THREAD

**Issue by RogerPodacter** [countries/countries#562]
I.e., [this line](https://github.com/hexorx/countries/blob/0e3f9bac4067886d0620ecf202cf90d8a06c3be9/lib/countries/data/countries/KP.yaml#L25)

I'm new to the gem so apologies if this has been discussed before (I searched around and didn't find anything) but it seems to me that the natural informal name for KP is "North Korea."

This is what Google Maps says and I think also what a non-expert would say if asked "Pyongyang is a city in what country?"

Thoughts?

**Comment by rposborne** [comment]
@RogerPodacter These are best seen as "slang" or informal my understanding is `North Korea` would be the defaults coming out of the translated names.

**Comment by RogerPodacter** [comment]
> the defaults coming out of the translated names.

I.e., [here](https://github.com/hexorx/countries/blob/93e9a340b5a5c402eae541a4b5f01154779fc175/lib/countries/cache/locales/en.json#L1)? Seems like this is all official names? And in general I don't see any way to get this gem to output the string "North Korea" which seems wrong to me.

Also, conversely, I don't see any reference to "Korea (North)" as a name for that country anywhere online.

I don't want to nitpick and I love the gem but would we lose anything by swapping "Korea (North)" with "North Korea"?

Keep up the great work regardless!

**Comment by talha-akram** [comment]
https://github.com/countries/countries/pull/681

I have created the PR for this, I ran in to an issue where I was getting errors because `North Korea` was not getting matched. Please consider adding it to the list of unofficial names, Thanks!

**Comment by pmor** [comment]
Fixed in #681
