### ISSUE TITLE
Norway subdivision keys incorrect

### ISSUE THREAD

**Issue by jjinkxy** [countries/countries#573]
The subdivision keys for Norway have an incorrect format ([file](https://github.com/hexorx/countries/blob/master/lib/countries/data/subdivisions/NO.yaml)).
https://github.com/hexorx/countries/blob/83f392b478f065411d6a4d48bab697b1eade72a3/lib/countries/data/subdivisions/NO.yaml#L26-L37
There should be no country code prefix e.g. `NO-`. Since I rely on the format of the keys and add the country code myself this led to invalid values such as `NO-NO-03`.

Correction:
The file has both. First norway's subdivisions with the key having the country code prefix and the attributes :name, :unofficial names, :translations (only :en though) and :geo, then later the keys in the correct format only with :translations for plentyful of countries. This should prob be combined.

Sadly, if I understand correctly, I should rather report this to https://salsa.debian.org/iso-codes-team/iso-codes/issues  ?

**Comment by rposborne** [comment]
I think we pull subdivisions from `http://www.unicode.org/repos/cldr/trunk/common/`  but I don't see Norway in there.  

So feel free to make a PR here.

**Comment by pmor** [comment]
Current version of the file matches the keys in https://www.iso.org/obp/ui/#iso:code:3166:NO
