### ISSUE TITLE
Definition of EU is missing Cyprus

### ISSUE THREAD

**Issue by evaneykelen** [countries/countries#587]
According this source https://europa.eu/european-union/about-eu/countries_en Cyprus belongs to the EU however `ISO3166::Country.find_all_countries_by_region('Europe').select { |country| country.in_eu? }.map(&:name)` does not yield `Cyprus`. Using `Asia` as the region does yield `Cyprus`. Doesn't it make more sense to place in it in Europe?

**Comment by timkrins** [comment]
The European Union is not a geographic region, so I would say that whether or not Cyprus belongs to the EU is irrelevant.

`ISO3166::Country.all.select { |country| country.in_eu? }.map(&:name)` includes Cyprus.

In the end it comes down to your source of truth. 

The UN classifies it geographically as in Western Asia (https://unstats.un.org/unsd/methodology/m49/)
