### ISSUE TITLE
Translation of pt-BR (Brazil) is getting wrongly from pt (Portugual)

### ISSUE THREAD

**Issue by pedrofurtado** [countries/countries#588]
@rposborne 

When I execute the following code the output for `pt-BR` is empty:

Code:
```ruby
ISO3166::Country.new(object.country).translations
```
Output:
```ruby
{
 "en"=>"Monaco",
 "zh-tw"=>nil,
 ...,
 "pt-br"=>nil,
 ...
}
```

But when executing this code, the translation of pt-BR (that is `Mônaco`) actually is getting from pt translation (that is `Mónaco`):

Code:
```ruby
ISO3166::Country.new('MC').translation('pt-BR')
# or
ISO3166::Country.new('MC').translation('pt-br')
```
Output:
```
"Mónaco"
```

I read the content of `https://github.com/hexorx/countries/blob/master/lib/countries/cache/locales/pt-br.json` file and the translation for `MC` key is available, with the value `Mônaco`.
The file `https://github.com/hexorx/countries/blob/master/lib/countries/translations.rb` has a fallback of `pt-br` to `pt`.

The translation for pt-BR is missing or is this a bug? If the translation is missing, what file could I open a PR with the translations for pt-br?

Thanks! :handshake:

**Comment by pedrofurtado** [comment]
@marcioJesus @willradi

**Comment by pedrofurtado** [comment]
@rposborne

**Comment by pedrofurtado** [comment]
@rposborne

**Comment by pedrofurtado** [comment]
@rposborne

**Comment by pedrofurtado** [comment]
@rposborne

**Comment by pedrofurtado** [comment]
@rposborne

**Comment by pedrofurtado** [comment]
@rposborne

**Comment by pmor** [comment]
This appears to have been fixed.
`ISO3166::Country.new('MC').translation('pt-br')` outputs `"Mônaco"` if `:'pt-br` is added to `ISO3166.configuration.locales`
