### ISSUE TITLE
Incomplete subdivision data

### ISSUE THREAD

**Issue by niborg** [countries/countries#590]
When trying to upgrade to 3.0 I came across a number of subdivisions that lack basic data:

```ruby
Country['fr'].subdivisions['V'] 
# => #<struct ISO3166::Subdivision name=nil, code=nil, unofficial_names=nil, geo=nil, translations={"en"=>"Rhône-Alpes"}, comments=nil>
```
It strikes me that at a bare minimum a subdivision should be validated to have a `name`.

**Comment by brendon** [comment]
I found this too. For New Zealand, there are now subdivisions for things like the North Island and South Island which aren't really used for addressing.

**Comment by brendon** [comment]
It appears to have been introduced here: https://github.com/hexorx/countries/commit/4ceacc806c84ad85ae101b5e9fcde72072da9980

The other option is to use the English translation (assuming there is an English translation).

**Comment by brendon** [comment]
Also the data has issues: https://github.com/hexorx/countries/commit/4ceacc806c84ad85ae101b5e9fcde72072da9980#diff-9266039bddf41feb51968547dc6655515fa8c0cbf0dadb2235c0ad9cc79d3ccfR259

No one calls it 'Marl'.

There's also two Chatham Islands: https://github.com/hexorx/countries/commit/4ceacc806c84ad85ae101b5e9fcde72072da9980#diff-9266039bddf41feb51968547dc6655515fa8c0cbf0dadb2235c0ad9cc79d3ccfR780

I think I'll roll this one back for now :)

**Comment by brendon** [comment]
Found this: https://github.com/loureirorg/city-state which has more accurate 'state' values.
