### ISSUE TITLE
Can we separate the country dataset from the Ruby code

### ISSUE THREAD

**Issue by itay-grudev** [countries/countries#636]
This project has one of the best country data sets I have seen and it may be useful for other projects as well. So my proposal is that we either:

* Extract all of the country data in a separate repository and include it as a git submodule
* I create a repository that gets updated whenever the dataset here is changed trigger via a webhook on commits.

This way other projects will be able to include the dataset directly as a git submodule and other languages will be able to benefit from it.

**Comment by itay-grudev** [comment]
Actually looks like a webhook is only optional, as it can also be done with a cron-job.

https://github.com/itay-grudev/iso-3166-yaml

**Comment by pmor** [comment]
Thanks for that, it works perfectly, and I feel it makes more sense than extracting the data, since our data is YAML-based, but I believe having JSON files might be more useful in some cases. Your approach lets us keep the YAML files as "master data", while also making JSON files available with no extra work

I forked your repos into our org repos, and will be updating the urls that are still pointing to `hexorx`'s original repo

- https://github.com/countries/countries-data-yaml
- https://github.com/countries/countries-data-json

**Comment by itay-grudev** [comment]
@pmor We should have done it via an ownership transfer so existing users of my repositories are gracefully redirected.

**Comment by itay-grudev** [comment]
I suppose it's not too late as long as you don't have users. I can merge your changes into my repos and then transfer ownership.

**Comment by itay-grudev** [comment]
This would entail:

1. I pull your changes into my 2 repos.
2. You delete your repos.
3. I transfer ownership of my two repos to `countries`.
4. You rename them from `iso-3166-` to `countries-data-`

**Comment by itay-grudev** [comment]
If you don't want to bother, I'll keep them running for a while with a deprication notice in the README and a link to your version.

**Comment by pmor** [comment]
@itay-grudev No, you have a very good point.

Ping me once you have the repos ready for transfer, in the meantime I'll add you to the organization

**Comment by itay-grudev** [comment]
@pmor I am ready. I merged your changes. I also renamed them to your specs. If you can add me to your org I can finish the transfer tomorrow.

Could you please delete your repositories?

**Comment by pmor** [comment]
@itay-grudev I sent you the invite, and I'm removing the repos now.

Thanks!

**Comment by itay-grudev** [comment]
@pmor Done.

**Comment by pmor** [comment]
@itay-grudev 🙇‍♂️ Great, thanks!
