### ISSUE TITLE
Missing Ñuble subdivision in Chile. #1

### ISSUE THREAD

**Issue by andre-b-fernandes** [countries/countries#642]
# Description

Chile does not possess all the ISO3166 subdivisions. Ñuble is missing.
Source: https://en.wikipedia.org/wiki/ISO_3166-2:CL

# How to reproduce

`ISO3166::Country["CL"].subdivision_names_with_codes(locale=ISO3166::Country["CL"].languages.first)`
=> `[["Región Aysén del General Carlos Ibáñez del Campo", "AI"], ["Región de Antofagasta", "AN"], ["Región de la Araucanía", "AR"], ["Región de Arica y Parinacota", "AP"], ["Región de Atacama", "AT"], ["Región del Bío Bío", "BI"], ["Región de Coquimbo", "CO"], ["Región de O’Higgins", "LI"], ["Región de Los Lagos", "LL"], ["Región de Los Ríos", "LR"], ["Región de Magallanes y de la Antártica Chilena", "MA"], ["Región del Maule", "ML"], ["Región Metropolitana de Santiago", "RM"], ["Región de Tarapacá", "TA"], ["Región de Valparaíso", "VS"]]`

# Desired output

=> `[["Región Aysén del General Carlos Ibáñez del Campo", "AI"], ["Región de Antofagasta", "AN"], ["Región de la Araucanía", "AR"], ["Región de Arica y Parinacota", "AP"], ["Región de Atacama", "AT"], ["Región del Bío Bío", "BI"], ["Región de Coquimbo", "CO"], ["Región de O’Higgins", "LI"], ["Región de Los Lagos", "LL"], ["Región de Los Ríos", "LR"], ["Región de Magallanes y de la Antártica Chilena", "MA"], ["Región del Maule", "ML"], ["Región Metropolitana de Santiago", "RM"], ["Región de Tarapacá", "TA"], ["Región de Valparaíso", "VS"], ["Ñuble", "NB"]]`

**Comment by silva96** [comment]
+1

**Comment by pmor** [comment]
This was fixed in 0ebfea2db8535903029739532cea89bb22463208
