### ISSUE TITLE
Add demonyms?

### ISSUE THREAD

**Issue by tsolar** [countries/countries#655]
It would be nice to have demonyms, and their translations

**Comment by pmor** [comment]
We actually have that in English, eg: `ISO3166::Country('ES').nationality`.

As for translations, see #349, it was never implemented, but it's still open. 

The current nationality data is in the YAML files, but for translations, I think the idea was to keep that data out of the YAML files to save memory. There's also the issue of a getting source for all the data.

(Closing, keeping #349 re: translations)
