### ISSUE TITLE
How to get continents only data? It seems missing

### ISSUE THREAD

**Issue by MahefaAbel** [countries/countries#668]
There is a case in which we have to get continents-only data, but it seems like not available.

**Comment by mathieujobin** [comment]
for context: https://stackoverflow.com/questions/66605555/how-to-list-all-continents-with-the-countries-gem

**Comment by pmor** [comment]
You can get it with `ISO3166::Country.pluck(:continent).flatten.uniq`, and as mentioned in the Stackoverflow thread, you can cache this in a constant if you need.

I don't really see a need for adding a new method for this.
