### ISSUE TITLE
Missing some UK "states": West Yorkshire and South Yorkshire

### ISSUE THREAD

**Issue by andrewhavens** [countries/countries#686]
I'm not very familiar with UK geography but it seems like two of these UK "states" are missing: West Yorkshire and South Yorkshire.

```ruby
states = country.states.values.map {|s| s.name || s.translations['en'] }.uniq
states.include? 'North Yorkshire' # true
states.include? 'South Yorkshire' # false
states.include? 'West Yorkshire' # false
states.include? 'East Riding of Yorkshire' # true
```

https://en.wikipedia.org/wiki/Yorkshire#Divisional
https://en.wikipedia.org/wiki/West_Yorkshire
https://en.wikipedia.org/wiki/South_Yorkshire

**Comment by pmor** [comment]
According to https://www.iso.org/obp/ui/#iso:code:3166:GB, those are not ISO 3166-2 subdivisions. They might be a lower level subdivision, or a statistical one, but in this gem we only include ISO 3166-2 data.
