### ISSUE TITLE
Wrong min_longitude for United States of America?

### ISSUE THREAD

**Issue by afdev82** [countries/countries#698]
Hi,

I'm using the [HERE Places API for autosuggest](https://developer.here.com/documentation/places/dev_guide/topics_api/resource-autosuggest.html) and I found that it was not working anymore for US.
After digging in, I found that the _min_longitude_ [here](https://github.com/countries/countries/blob/4118fd556e6f2d9a8763ce84182849dfd64f05dd/lib/countries/data/countries/US.yaml#L49) and the _lng_ [here](https://github.com/countries/countries/blob/4118fd556e6f2d9a8763ce84182849dfd64f05dd/lib/countries/data/countries/US.yaml#L56) are not negative numbers, so I get a wrong bounding box.
I don't understand how it could work before, but it looks to me that the correct number should be -170.5957 and not 170.5957.
If I use the -170.5957 in the HERE API is working fine.

Let me know if I can help to solve this issue.
Many thanks for your support!

**Comment by pmor** [comment]
I'm guessing this is a similar issue to #535, because of US overseas territories in the Pacific?

In any event, similar to the UK bounding box issue, I'll be updating the US coordinates to saner values.
