### ISSUE TITLE
Incorrect unofficial names for Andorra and Barbados 

### ISSUE THREAD

**Issue by melissaayers** [countries/countries#699]
It seems Andorra and Barbados are listed as Barbade, Andorre in the unofficial name listing 

`ISO3166::Country.all.map { |c| c.unofficial_names[0] }`

`["Tajikistan", "Jamaica", "Haiti", "São Tomé and Príncipe", "Montserrat", "United Arab Emirates", "Pakistan", "Netherlands", "Luxembourg", "Belize", "Iran", "Bolivia", "Uruguay", "Ghana", "Saudi Arabia", "Côte D'Ivoire", "Saint Martin", "French Southern Territories", "Anguilla", "Qatar", "Sint Maarten", "Libya", "Bouvet Island", "Papua New Guinea", "Kyrgyzstan", "Equatorial Guinea", "Western Sahara", "Niue", "Puerto Rico", "Grenada", "South Korea", "Heard and McDonald Islands", "San Marino", "Sierra Leone", "Congo (Dem. Rep.)", "Macedonia", "Turkey", "Algeria", "Georgia", "Palestine", "Barbade", "Ukraine", "Guadeloupe", "French Polynesia", "Namibia", "Botswana", "Syria", "Togo", "Dominican Republic", "Antarctica", "Switzerland", "Madagascar", "Faroe Islands", "British Virgin Islands", "Gibraltar", "Brunei", "Laos", "Iceland", "Estonia", "United States Minor Outlying Islands", "Lithuania", "Serbia", "Mauritania", "Andorre", "Hungary", "Tokelau", "Malaysia", "Angola", "Cape Verde", "Norfolk Island", "Panama", "Guinea-Bissau", "Belgium", "Portugal", "United Kingdom", "Isle of Man", "United States", "Yemen", "Hong Kong", "Azerbaijan", "Cocos (Keeling) Islands", "Mali", "Slovakia", "Vanuatu", "East Timor", "Croatia", "Suriname", "Mauritius", "Czech Republic", "Saint Pierre and Miquelon", "Lesotho", "Samoa", "Comoros", "Italy", "Burundi", "Wallis and Futuna", "Guinea", "Singapore", "Colombia", "China", "Aruba", "Morocco", "Finland", "Vatican City", "Zimbabwe", "Cayman Islands", "Bahrain", "Paraguay", "Ecuador", "Liberia", "Russia", "Poland", "Oman", "Malta", "South Sudan", "Germany", "Turkmenistan", "Svalbard and Jan Mayen", "Myanmar", "Trinidad and Tobago", "Israel", "Bangladesh", "Nauru", "Sri Lanka", "Uganda", "Nigeria", "Bonaire, Sint Eustatius and Saba", "Mexico", "Curaçao", "Slovenia", "Mongolia", "Canada", "Åland Islands", "Vietnam", "Taiwan", "Japan", "British Indian Ocean Territory", "Romania", "Bulgaria", "Guam", "Brazil", "Armenia", "Zambia", "Djibouti", "Jersey", "Austria", "Cameroon", "Sweden", "Fiji", "Kazakhstan", "Greenland", "Guyana", "Christmas Island", "Malawi", "Tunisia", "South Africa", "Tonga", "Cyprus", "Maldives", "Pitcairn", "Rwanda", "Nicaragua", "Saint Kitts and Nevis", "Benin", "Ethiopia", "Gambia", "Tanzania", "Saint Vincent and the Grenadines", "Falkland Islands", "Sudan", "Monaco", "Australia", "Chile", "Denmark", "France", "Turks and Caicos Islands", "Cuba", "Albania", "Mozambique", "Bahamas", "Niger", "Guatemala", "Liechtenstein", "Nepal", "Burkina Faso", "Palau", "Kuwait", "India", "Gabon", "Tuvalu", "Macao", "Saint Helena", "Moldova", "Cook Islands", "Argentina", "Seychelles", "Ireland", "Spain", "Lebanon", "Bermuda", "Réunion", "Kiribati", "Antigua and Barbuda", "Martinique", "El Salvador", "Jordan", "Thailand", "Somalia", "Marshall Islands", "Congo", "Korea (North)", "French Guiana", "Bosnia and Herzegovina", "Mayotte", "South Georgia", "Kenya", "Peru", "Bhutan", "Swaziland", "Costa Rica", "Chad", "Dominica", "New Caledonia", "Greece", "Guernsey and Alderney", "Honduras", "Virgin Islands of the United States", "Central African Republic", "Senegal", "Afghanistan", "Northern Mariana Islands", "Philippines", "Belarus", "Latvia", "Norway", "Egypt", "Cambodia", "Iraq", "Saint Lucia", "New Zealand", "Saint Barthélemy", "Uzbekistan", "Indonesia", "Eritrea", "Venezuela", "Micronesia", "Solomon Islands", "Crna Gora", "American Samoa"]`

**Comment by pmor** [comment]
Those seem to be French names for Andorra and Barbados. The unofficial names list (currently a bit of a mess) includes names in different languages and is mostly used as a searchable field to find countries from unofficial names.

If you're looking for a list of "common names" in English, then `ISO3166::Country.translations` is probably closer to your needs.
