### ISSUE TITLE
uninitialized constant InmycountryController::Country

### ISSUE THREAD

**Issue by johanlajili** [countries/countries#70]
Probably a beginner question, but I take the risk to ask.
I'm creating my first Ruby application (more of a javascript developer), and countries is the first gem library I'm using, so, i may not be aware of every step. What I did:
I added

``` ruby
gem 'countries'
gem 'country_select'
```

to the gemfile on the root of my project.
I ran **bundle update**, in my project directory (btw, i'm on mac OSX Mountain lion)
and if I do a **gem list**, it shows me the packages are installed:

``` ruby
gem list
[...]
countries (0.9.2)
country_select (1.1.3)
[...]
```

So everything seems to be good. But then, when in my controller I do

``` ruby
c = Country.new('US')
```

I get the following error **_uninitialized constant InmycountryController::Country**_
(inmycountry is the name of my app).

I then tried different vodoo fix from things i find from the internet, esp.

``` ruby
require("countries")
```

but it says: **_cannot load such file -- countries**_
Am I doing something wrong?

rails version: 3.2.13
ruby version 2.0.0p0

**Comment by prakash014** [comment]
in my case i had forgotten to restart server after i installed this gem, hence controllor was throwing error <code> cannot load such file -- iso3166 </code>

**Comment by sibinx7** [comment]
Try to use only 
```
gem 'countries'
```
in Gem file..


I also had same issue.
