### ISSUE TITLE
Add Wales as a country

### ISSUE THREAD

**Issue by asungur** [countries/countries#701]
I am aware that countries are using `ISO 3166-1` not `3166-2`, so this is not necessarily a bug.
Wales became a country with `3166-2` so my question is when you are planning to move countries to `ISO 3166-2` standard?

**Comment by pmor** [comment]
Wales appears as `GB-WLS` in the `ISO 3166-2` (https://en.wikipedia.org/wiki/ISO_3166-2:GB) and it's considered a subdivision of `GB`, and I'm not finding any two-letter country code for Wales.

This gem already supports `ISO 3166-2` subdivisions, Wales can be found under `ISO3166::Country['GB'].subdivisions['WLS']`.
