### ISSUE TITLE
Serbian translation for North Macedonia is incorrect

### ISSUE THREAD

**Issue by lavaturtle** [countries/countries#703]
In the Serbian (`sr`) translations, `MK` (the ISO 3166 code for North Macedonia) is mapped to "Нова Каледонија". But "Нова Каледонија" appears to be the Serbian name for New Caledonia. I think (based on Wikipedia; I personally don't read Serbian) the correct translation should be something like "Северна Македонија".

**Comment by pmor** [comment]
I don't read Sebian either, but "Северна Македонија" looks correct, and this seems to be an issue with the [I18Data](https://github.com/grosser/i18n_data) gem that we use. I'll report it upstream.

**Comment by lavaturtle** [comment]
Thanks!

**Comment by pmor** [comment]
Fixed in #705, I'll try to have a new release soon
