### ISSUE TITLE
Subdivision translations for some latvian subdivisions nil in countries 4.1.2

### ISSUE THREAD

**Issue by fschwahn** [countries/countries#718]
After updating to countries 4.1.2 we are seeing errors in our test suite because the following latvian subdivisions don't have any translations (ie. `subdivision.translations` returns `nil` instead of `{}`):
- Augšdaugavas novads
- Dienvidkurzemes Novads
- Valmieras Novads

This is not the case for any other country / subdivision, so I believe this is a regression in the recent update of subdivision data. It is a breaking change at least for us.

If possible, it would be great if an empty hash could always be returned in case no translations are present, as to facilitate lookups such as: `subdivision.translations[I18n.locale.to_s] || subdivision.name`.

**Comment by pmor** [comment]
The 3 subdivisions were added to the ISO list on 2021-11-25 (see https://www.iso.org/obp/ui/#iso:code:3166:LV), and it looks like the CLDR repo (https://github.com/unicode-org/cldr) doesn't have any translation data for those yet.

I'm going to ensure the translation hash for these subdivisions are not empty, that should allow you to do the lookup without error.

**Comment by pmor** [comment]
New release with the fix https://github.com/countries/countries/releases/tag/v4.1.3

**Comment by fschwahn** [comment]
That was quick 😳 thanks! 😄
