### ISSUE TITLE
find_by_any_name not searching in alpha2 field

### ISSUE THREAD

**Issue by GMolini** [countries/countries#750]
Gem version:   countries (5.0.1)
It seems like the find_country_by_any_name function is not searching in the alpha2 field. I understood from the documentation that it would search everywhere

From my rails console output:
```
irb(main):161:0> ISO3166::Country.find_country_by_any_name("FR")
=> nil
irb(main):162:0> ISO3166::Country.find_country_by_alpha2("FR")
=> #<ISO3166::Country:0x000055d86dcef4a0 @country_data_or_code={"address_format"=>"{{recipient}}\n{{street}}\n{{postalcode}} {{city}}\n{{countr..
```

**Comment by pmor** [comment]
`#find_by_any_name` searches all the **name** attributes, meaning official, unofficial and translated names. Alpha2 and Alpha3 are country codes, not names, and the `#find_by_name` that was renamed `#find_by_any_name` didn't search in the codes either.

I'll try to reorganise the README a bit to make it clearer

**Comment by GMolini** [comment]
ok, thats cleared up. thanks.

**Comment by pmor** [comment]
Also, if you already have the alpha-2 country code, you can call `ISO3166::Country['FR']`

**Comment by GMolini** [comment]
yeah, thing was, i had mixed data, some alpha2 names and some 'normal' names. So i first tried just searching each string with that function. Now im just checking whether the string is of length two before searching.
