### ISSUE TITLE
Possibly incorrect common name

### ISSUE THREAD

**Issue by manastyretskyi** [countries/countries#753]
Hello,
I've noticed that `common_name` of Iran is `Iran, Islamic Republic of` and I don't think this is correct, I would expect it to be just `Iran`, or at least `Islamic Republic of Iran`

```irb
irb(main):024:0> ISO3166::Country.new("IR").common_name
=> "Iran, Islamic Republic of"
```

**Comment by pmor** [comment]
Yep, you're right. Thanks for the report, I'll push out a correction soon
