### ISSUE TITLE
Get all regions and cities of a country

### ISSUE THREAD

**Issue by phlegx** [countries/countries#760]
Hi there!

Does the countries gem also offer to get regions and cities from a certain country?

If yes, what is the best way to do this?

If no, are there any plans to implement this? There is a nice database available here: https://github.com/dr5hn/countries-states-cities-database which could be used.

best
Martin

**Comment by pmor** [comment]
Hi,

We have the ISO3166-2 subdivisions, which for some countries are regions or states, but for other countries are smaller units such as municipalities. See https://github.com/countries/countries#subdivisions--states

We don't have city data, nor do we have a plan to add it, as the dataset for that is likely quite large and we keep most data loaded in memory, so it would require a substantial rewrite for this gem to efficiently handle large datasets. It's also not part of any ISO standard, and we try to stick to data that is published as part of some standard or "official" source.
