### ISSUE TITLE
implementation adds languages to underlying I18n array

### ISSUE THREAD

**Issue by Janne-ka** [countries/countries#768]
First implementation gets original array
    def initialize
      @locales = default_locales

 def default_locales
      locales = if Object.const_defined?('I18n') && I18n.respond_to?(:available_locales)
                  I18n.available_locales
     
Then it adds languages to it (several places), in this case :en
 ISO3166.configuration.locales = ISO3166.configuration.locales.append(:en).uniq

suggested fix: at default_locales create a copy rather than use original:   I18n.available_locales.dup

**Comment by Janne-ka** [comment]
simplest workaround for me was to add few lines to application.rb since I wanted to use I18n defined languages:
		config.after_initialize do
			ISO3166.configure do |config|
				config.locales = I18n.available_locales.dup
			end
		end

**Comment by 1klap** [comment]
I noticed this as well
@Janne-ka thanks the workaround

it is also possible to monkey patch this by putting the following in a file under `config/initializers/monkey_patches.rb`
```ruby
module ISO3166
  class Configuration
    def default_locales
      locales = if Object.const_defined?('I18n') && I18n.respond_to?(:available_locales)
                  I18n.available_locales.dup
                else
                  [:en]
                end
      locales.empty? ? [:en] : locales
    end
  end
end
```

**Comment by pmor** [comment]
Thanks for the report and the workaround. I'll try to get a fix in soon
