### ISSUE TITLE
Countries gem >= 5.0 won't work with JRuby 9.3.x

### ISSUE THREAD

**Issue by nehresma** [countries/countries#774]
Countries releases 5.0 and later require Ruby version >= 2.7.  JRuby 9.3 (the latest version released) supports Ruby up through 2.6.  The JRuby 9.4 series is actively being worked on and it will support Ruby versions 2.7 and 3.0 (https://github.com/jruby/jruby/issues/6878).  However it hasn't been released yet.

This means that JRuby projects are unable to use the most recent versions of this gem.

As of 6ae7f346f08c3c77b2f494ec66d7d166a2ef7847, all specs still pass with Ruby 2.6.

So since I'm in a position of needing to use the latest Countries gem under JRuby 9.3 at the moment and all the Countries specs still pass with older versions of Ruby, does anyone here foresee any issue with me forking the repo, adjusting the required Ruby version downward, and then using my fork directly in my Gemfile?

**Comment by pmor** [comment]
@nehresma If the specs are green, I think you should be fine.
