### ISSUE TITLE
State name for state_code 972 in France is nil

### ISSUE THREAD

**Issue by tambakoo** [countries/countries#775]
Hi. I am getting the state value as nil for state_code 972 for France. Please refer attachment. Is this expected behaviour ?
Gem version:  5.0.2
![Screenshot 2022-10-12 at 5 58 59 PM](https://user-images.githubusercontent.com/31440367/195343188-a94796ab-c307-474a-8ef7-ca67dfe6d9d3.png)

**Comment by pmor** [comment]
@tambakoo I've just checked on the latest version of the gem and `972` is returning "Martinique", as expected.

What version of the gem are you using?

**Comment by tambakoo** [comment]
@pmor I am on 5.0.2

**Comment by pmor** [comment]
5.0.2 did have incorrect data for FR subdivisions, it was fixed in https://github.com/countries/countries/commit/243104318dbe15fb0647ec8a107f09c1084d4ed7 and released in 5.1.0
