### ISSUE TITLE
Find country based on it's subdivision

### ISSUE THREAD

**Issue by oskargargas** [countries/countries#786]
Hi! I use a service that sometimes returns subdivision instead of country. For example it might say `Scotland` instead of `United Kingdom`. I need to parse it correctly back to the country (UK). I don't see any way right now. 

In ideal scenario I would do:
`ISO3166::Country.find_all_by(:subdivision, 'Scotland')`

Example:
https://opencorporates.com/companies/gb/SC524841
https://api.opencorporates.com/companies/gb/SC524841 (might not work without API key. Should be free but often is IP blocked)

**Comment by oskargargas** [comment]
Other interesting thing is that `ISO3166::Country.find_all_by(:any_name, 'England')` finds `UK` but `Scotland, Wales, Northern Ireland` doesn't. 
All of those are `ISO 3166-2` subdivision names.

**Comment by pmor** [comment]
Good suggestion 👍 I'll look into it.

As for the case of England -> UK, it's because `England` is listed as an `unnoficial_name` for `UK`

**Comment by pmor** [comment]
Latest release added `Country#subdivision_names`, so `ISO3166::Country.find_all_by(:subdivision_names, 'Scotland')` should now work. It's likely a bit slow compared to other searches, since it requires loading all subdivisions for all countries.
