### ISSUE TITLE
Country code AN

### ISSUE THREAD

**Issue by pioter** [countries/countries#791]
Can you add https://www.iso.org/obp/ui/#iso:code:3166:AN ?

**Comment by pmor** [comment]
@pioter From what I can see, Netherlands Antilles is no longer a constituent country of the Netherlands, having been split into Bonaire, Saint Eustatius and Saba (`BQ`), Curaçao (`CW`) and Sint Maarten (`SX`).

The `AN` code is still present as a "reserved" code, but the corresponding country no longer exists. 

At this time, we don't have support for countries that no longer exist.
