### ISSUE TITLE
Wrong 'gn' translation for Malaysia

### ISSUE THREAD

**Issue by sdecourcel** [countries/countries#797]
`ISO3166::Country.find_country_by_any_name("Mexico")`  => Malaysia

There may be a wrong ‘gn’ translation for Malaysia :

![2023-04-11_20-04_wrong_translation_for_malaysia_gn_locale](https://user-images.githubusercontent.com/23135475/231252190-9eb94818-527f-434e-a55c-f383ced222a2.png)

**Comment by pmor** [comment]
Well spotted, thanks!
