### ISSUE TITLE
Inconsistency in Taiwan's data

### ISSUE THREAD

**Issue by pablobm** [countries/countries#809]
Sorry to file out a new one about Taiwan! I understand that maintainers will be fed up with this topic, but I do think there is an issue of inconsistent data, as opposed to a political issue.

Presently, the data file [TW.yaml](https://github.com/countries/countries/blob/master/lib/countries/data/countries/TW.yaml) lists two incompatible names for this territory:

```
  iso_long_name: The Republic of China
  iso_short_name: Taiwan, Province of China
```

In broad terms, the first one is an "anti-China" term (ie: Taiwan as different from the _People's_ Republic of China), while the second one is a "pro-China" term (ie: Taiwan as constituent part of the PRC).

I believe that ISO 3166 uses the second term (https://www.iso.org/obp/ui/#iso:code:3166:TW), so if this gem chooses to adopt the position of sticking to that standard, then that's what it should use.

(Incidentally, that short name is not really short, is it?)

**Comment by pmor** [comment]
Well spotted. While "The Republic of China" is supposed to be the official name, ISO doesn't have a long name set for Taiwan, so I think we should use the short name in both fields. 

I'll push a fix in a bit, and will go out with the next release

(There's worse as far as short names go... UK has "United Kingdom of Great Britain and Northern Ireland" as the short name)
