### ISSUE TITLE
Add Ottoman Roguefort Map

### ISSUE THREAD

**Issue by Limaeoha** [countries/countries#811]
![Screenshot_20230727-044343](https://github.com/countries/countries/assets/90700465/ecc7b36e-6ec6-4502-84b4-2983afcc1c80)
Ottoman Roguefort wasn't state 😂

**Comment by pmor** [comment]
Again, we do not deal with historical countries, and we we also don't have any map data, so you might be looking at the wrong repo

**Comment by Limaeoha** [comment]
![Uploading Screenshot_20230729-031311.png…]()

**Comment by Limaeoha** [comment]
![Screenshot_20230729-031311](https://github.com/countries/countries/assets/90700465/84553876-2228-494d-b5b4-f2e9d7f61ea4)
Ottoman Pa
