### ISSUE TITLE
Add Ottoman Empire Flag

### ISSUE THREAD

**Issue by Limaeoha** [countries/countries#812]
![무제9_20230728042102](https://github.com/countries/countries/assets/90700465/7c8a3ee2-ec35-4526-bd83-73d372539210)

**Comment by Limaeoha** [comment]
![Ottoman_flag svg](https://github.com/countries/countries/assets/90700465/63afbdde-c37f-4713-ab00-3d6f0a295955)

**Comment by pmor** [comment]
I think you might be mistaken? This repository does not deal with historical countries, and we use emoji for flags
