### ISSUE TITLE
Delphi port

### ISSUE THREAD

**Issue by zedalaye** [countries/countries#842]
Hi. For those interested, I just pushed the very first version of the Delphi (yes) port of this awesome gem. 
Data come from `countries-data-json`

I've tried to respect the API as much as possible and I think the result is quite cool :)

Can you review the contributions/licensing part of the README and tell me if it doesn't suit : https://github.com/zedalaye/Delphi-Countries/tree/main?tab=readme-ov-file#note-on-patchespull-requests

Thank you for this very useful piece of code.

**Comment by pmor** [comment]
Thanks!

That part of the README looks fine to me 👍
