### ISSUE TITLE
Spain misses a lot of entries for the languages

### ISSUE THREAD

**Issue by rbozan** [countries/countries#852]
https://github.com/countries/countries/blob/8d72392fda72071c88dff1545d94f4cc013dc537/lib/countries/data/countries/ES.yaml#L38-L39

There are many languages missing for Spain. Wikipedia has a list of these languages: https://en.wikipedia.org/wiki/Languages_of_Spain#Present-day_languages

**Comment by pmor** [comment]
Well spotted! I'll push a fix soon!
