### ISSUE TITLE
Missing countries translations in Czech

### ISSUE THREAD

**Issue by mmadyda** [countries/countries#867]
Hi,
cz.json file is missing.

**Comment by pmor** [comment]
Hi, if you're referring to the json files in `lib/countries/cache/locales`, the Czech language file is `cs.json` (https://github.com/countries/countries/blob/a8ea7e21e3c4316e4a0e1322b0ad239d0c8a0392/lib/countries/cache/locales/cs.json)

The files use ISO 639-2 language codes, and code for Czech is actually `cs`, not `cz`.

**Comment by mmadyda** [comment]
Thank you for your answer, the `cs` code works.
